In [1]:
# import the dependencies
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

In [2]:
import os

In [39]:
import geopy

In [10]:
# constants
DATA_DIR = ""

In [11]:
os.path.join(DATA_DIR,"Snow_Emergency_Grant_Tows_2015.geojson")

'Snow_Emergency_Grant_Tows_2015.geojson'

In [12]:
grant_tows = gpd.read_file(os.path.join(DATA_DIR,"Snow_Emergency_Grant_Tows_2015.geojson"))

In [13]:
grant_tows.head()

,FID,X,Y,Call_Taken,Location,Day,geometry
0,1,-1.038025e+07,5.623291e+06,2015-12-29T00:00:00,2326 Central Ave NE,Day 1,POINT (-93.24740688343616 45.01123618428048)
1,2,-1.038334e+07,5.618287e+06,2015-12-29T00:00:00,618 1ST N,Day 1,POINT (-93.27510825313226 44.97945116173709)
2,3,-1.038308e+07,5.615996e+06,2015-12-29T00:00:00,1824 3rd ave s,Day 1,POINT (-93.27281155185176 44.96488946723947)
3,4,-1.038080e+07,5.614751e+06,2015-12-29T00:00:00,2519 bloomington ave s,Day 1,POINT (-93.25235251858196 44.95697462618004)
4,5,-1.038023e+07,5.626288e+06,2015-12-29T00:00:00,3447 Central Ave NE,Day 1,POINT (-93.24719240972475 45.03026988637581)

In [18]:
def xcoord (point):
    if point:
        return point.x
    else:
        return None

In [21]:
gpd.tools.geocode?

In [34]:
missing_locations = []
for row in grant_tows.itertuples():
    if not row.geometry:
        print(row.Location)
        missing_locations.append(row.Location + ", Minneapolis, MN")
        # print(missing_locations)

chicago ave s/34th st e
601 N 7th St
350 van white mem
279 w 15th st
132 w 15th st
279 w 15th st
160 w 15th
19 w 15th st
708 VAN WHITE
1120 van white ave n
1128 van white
59 n 4th ave
3825 3rd
1603 24th AV s
525 N 2ND ST
14th and washington
160 w 15th st
1815 noth emerson
501 e 15th St
1158 van white Blvd n
2715 east 50th street
2303 9 th sts
14 ave se
14th ave se 8th st se
2586 w 43rd st
386 w 15th st
2001 S 9th st
1215w 26th
513
510 n 1st st
386 w 15th st
2811 blaisedale s
5044 5th at s
2322 butler pl
368 w15th st
368 w15th st
328 w15th
160 w 15th st
15th and LaSalle
875 9th ave s.e.
469 W 15th ST
160 w 15th st
3550 e 46th st
1341 n 2nd st
10th and washington
27 w 15th st
Se hennepin/18 ave se
411 N 2ND ST
Willow and grant
3076 Emerson Abe n Minneapolis
507 e 15th
2636 Emerson ace n Minneapolis
University and 8th ave
395 2nd st s e
NE Grand & Lowry
528 e 15th st
Grand & Lowry
1923 1rst st s
E 16th st/ Chicago
3330 Fremont
Grand & Lowry
2321 n 2nd st
3550 E 46TH ST
528 e15th st
4th and 8th
604 e15th st
503 E 15th St
3540
408 erie nd ave se
1416 e 41st st
2418  N 3rd st
15th / oak grove
801 n. washington ave.
17th como ave s e
13th Ave & Grand
13th Ave & Grand
2752 e 38 st
916 N Washington Ave
13th Ave & Grand
2205 blaisdell s
2245 blaidsdell ave
rear
2311 blaisedale s
829 3rd st n space no. 1829
507 e 15th st
507 E 15th St
Minneapolis
University and 8
656 e 15th
13 Ave NE
3614 Fremont
2408 blaisdale
800 n Washington ave
4349 28th
1726 e 15th st
Franklin/ blaisdale
15th ave se
2518 Fremont ave n Minneapolis
726 E 15TH ST
E 16th/ Chicago
726 E 15TH ST
606 e 15th st
1300. Blk harmon pl
2106 Fremont ace n Minneapolis
2427 blaisdell s
2511 CHICAGO AVE A
4729 2oth ave so
4130 Fremont ave n Minneapolis
2678 WEST 43RD ST
14th&LaSalle Ave
13th & Grand
2570 W 43rd ST
Walnut st se and Delaware
2727 44st w
15th/ lasalle
13 ave se
1521 lascell
1230 8th st s e
3915 Fremont ace n Minneapolis
2498 blaisdale
26th/ blaisdale
2697 Blas dale ave s
2663 blaidsdell
672 e 15th  st
S 19th and Franklin f rd
2552 w 43rd st
1575 lesalle ave s
1545 le salle Ave s
2707 blaisdale
Mncis parking
726 e 15th
43rd/upton
13th & Marshall
907 19tg ave s
1430 lesalle
2200 N 4th st
2312 N 4th st
1100 uptown  Ave N
2322 N 4th st
900 Iving Ave N
1104 14 th ave s e
1914 Clinton ace s
3404 Holmes
3532 Holmes
1220 GRAND ST NE
1217 talmage ave s e
3112 Holmes
128 9th ave ne
2318 N 4th st
2222 N 4th st
2214 N 4th st
3118 Holmes
3554 Holmes
2210 N 4th st
1047 13th ave s e
3217 HOLMES
1033 16th ave s e
421 giarad ter
638 pol st ne
1502 e 33rd st
3228 15th a ve s
1108 14th ave s e
3142 16tj ave
204 E 18th st
612 Knox ave n
1518 5th st s.e.
1048 16th ave s e
1074 14th ave s e
1908 Neuton Ave N
1056 24th ave s e
1329 7 th se
7th and 14th ST SE
1015 16th ave s e
84'6 8th Ave n
705 Lyndale place
929 12th ave s e
1101 22nd ave s e
2737 peirce st ne
2653 james abe n
33oak grove st

In [35]:
missing_locations

['chicago ave s/34th st e, Minneapolis, MN',
 '601 N 7th St, Minneapolis, MN',
 '350 van white mem, Minneapolis, MN',
 '279 w 15th st, Minneapolis, MN',
 '132 w 15th st, Minneapolis, MN',
 '279 w 15th st, Minneapolis, MN',
 '160 w 15th, Minneapolis, MN',
 '19 w 15th st, Minneapolis, MN',
 '708 VAN WHITE, Minneapolis, MN',
 '1120 van white ave n, Minneapolis, MN',
 '1128 van white, Minneapolis, MN',
 '59 n 4th ave, Minneapolis, MN',
 '3825 3rd, Minneapolis, MN',
 '1603 24th AV s, Minneapolis, MN',
 '525 N 2ND ST, Minneapolis, MN',
 '14th and washington, Minneapolis, MN',
 '160 w 15th st, Minneapolis, MN',
 '1815 noth emerson, Minneapolis, MN',
 '501 e 15th St, Minneapolis, MN',
 '1158 van white Blvd n, Minneapolis, MN',
 '2715 east 50th street, Minneapolis, MN',
 '2303 9 th sts, Minneapolis, MN',
 '14 ave se, Minneapolis, MN',
 '14th ave se 8th st se, Minneapolis, MN',
 '2586 w 43rd st, Minneapolis, MN',
 '386 w 15th st, Minneapolis, MN',
 '2001 S 9th st, Minneapolis, MN',
 '1215w 26th, Minneapolis, MN',
 '513, Minneapolis, MN',
 '510 n 1st st, Minneapolis, MN',
 '386 w 15th st, Minneapolis, MN',
 '2811 blaisedale s, Minneapolis, MN',
 '5044 5th at s, Minneapolis, MN',
 '2322 butler pl, Minneapolis, MN',
 '368 w15th st, Minneapolis, MN',
 '368 w15th st, Minneapolis, MN',
 '328 w15th, Minneapolis, MN',
 '160 w 15th st, Minneapolis, MN',
 '15th and LaSalle, Minneapolis, MN',
 '875 9th ave s.e., Minneapolis, MN',
 '469 W 15th ST, Minneapolis, MN',
 '160 w 15th st, Minneapolis, MN',
 '3550 e 46th st, Minneapolis, MN',
 '1341 n 2nd st, Minneapolis, MN',
 '10th and washington, Minneapolis, MN',
 '27 w 15th st, Minneapolis, MN',
 'Se hennepin/18 ave se, Minneapolis, MN',
 '411 N 2ND ST, Minneapolis, MN',
 'Willow and grant, Minneapolis, MN',
 '3076 Emerson Abe n Minneapolis, Minneapolis, MN',
 '507 e 15th, Minneapolis, MN',
 '2636 Emerson ace n Minneapolis, Minneapolis, MN',
 'University and 8th ave, Minneapolis, MN',
 '395 2nd st s e, Minneapolis, MN',
 'NE Grand & Lowry, Minneapolis, MN',
 '528 e 15th st, Minneapolis, MN',
 'Grand & Lowry, Minneapolis, MN',
 '1923 1rst st s, Minneapolis, MN',
 'E 16th st/ Chicago, Minneapolis, MN',
 '3330 Fremont, Minneapolis, MN',
 'Grand & Lowry, Minneapolis, MN',
 '2321 n 2nd st, Minneapolis, MN',
 '3550 E 46TH ST, Minneapolis, MN',
 '528 e15th st, Minneapolis, MN',
 '4th and 8th, Minneapolis, MN',
 '604 e15th st, Minneapolis, MN',
 '503 E 15th St, Minneapolis, MN',
 '3540, Minneapolis, MN',
 '408 erie nd ave se, Minneapolis, MN',
 '1416 e 41st st, Minneapolis, MN',
 '2418  N 3rd st, Minneapolis, MN',
 '15th / oak grove, Minneapolis, MN',
 '801 n. washington ave., Minneapolis, MN',
 '17th como ave s e, Minneapolis, MN',
 '13th Ave & Grand, Minneapolis, MN',
 '13th Ave & Grand, Minneapolis, MN',
 '2752 e 38 st, Minneapolis, MN',
 '916 N Washington Ave, Minneapolis, MN',
 '13th Ave & Grand, Minneapolis, MN',
 '2205 blaisdell s, Minneapolis, MN',
 '2245 blaidsdell ave, Minneapolis, MN',
 'rear, Minneapolis, MN',
 '2311 blaisedale s, Minneapolis, MN',
 '829 3rd st n space no. 1829, Minneapolis, MN',
 '507 e 15th st, Minneapolis, MN',
 '507 E 15th St, Minneapolis, MN',
 'Minneapolis, Minneapolis, MN',
 'University and 8, Minneapolis, MN',
 '656 e 15th, Minneapolis, MN',
 '13 Ave NE, Minneapolis, MN',
 '3614 Fremont, Minneapolis, MN',
 '2408 blaisdale, Minneapolis, MN',
 '800 n Washington ave, Minneapolis, MN',
 '4349 28th, Minneapolis, MN',
 '1726 e 15th st, Minneapolis, MN',
 'Franklin/ blaisdale, Minneapolis, MN',
 '15th ave se, Minneapolis, MN',
 '2518 Fremont ave n Minneapolis, Minneapolis, MN',
 '726 E 15TH ST, Minneapolis, MN',
 'E 16th/ Chicago, Minneapolis, MN',
 '726 E 15TH ST, Minneapolis, MN',
 '606 e 15th st, Minneapolis, MN',
 '1300. Blk harmon pl, Minneapolis, MN',
 '2106 Fremont ace n Minneapolis, Minneapolis, MN',
 '2427 blaisdell s, Minneapolis, MN',
 '2511 CHICAGO AVE A, Minneapolis, MN',
 '4729 2oth ave so, Minneapolis, MN',
 '4130 Fremont ave n Minneapolis, Minneapolis, MN',
 '2678 WEST 43RD ST, Minneapolis, MN',
 '14th&LaSalle Ave, Minneapolis, MN',
 '13th & Grand, Minneapolis, MN',
 '2570 W 43rd ST, Minneapolis, MN',
 'Walnut st se and Delaware, Minneapolis, MN',
 '2727 44st w, Minneapolis, MN',
 '15th/ lasalle, Minneapolis, MN',
 '13 ave se, Minneapolis, MN',
 '1521 lascell, Minneapolis, MN',
 '1230 8th st s e, Minneapolis, MN',
 '3915 Fremont ace n Minneapolis, Minneapolis, MN',
 '2498 blaisdale, Minneapolis, MN',
 '26th/ blaisdale, Minneapolis, MN',
 '2697 Blas dale ave s, Minneapolis, MN',
 '2663 blaidsdell, Minneapolis, MN',
 '672 e 15th  st, Minneapolis, MN',
 'S 19th and Franklin f rd, Minneapolis, MN',
 '2552 w 43rd st, Minneapolis, MN',
 '1575 lesalle ave s, Minneapolis, MN',
 '1545 le salle Ave s, Minneapolis, MN',
 '2707 blaisdale, Minneapolis, MN',
 'Mncis parking, Minneapolis, MN',
 '726 e 15th, Minneapolis, MN',
 '43rd/upton, Minneapolis, MN',
 '13th & Marshall, Minneapolis, MN',
 '907 19tg ave s, Minneapolis, MN',
 '1430 lesalle, Minneapolis, MN',
 '2200 N 4th st, Minneapolis, MN',
 '2312 N 4th st, Minneapolis, MN',
 '1100 uptown  Ave N, Minneapolis, MN',
 '2322 N 4th st, Minneapolis, MN',
 '900 Iving Ave N, Minneapolis, MN',
 '1104 14 th ave s e, Minneapolis, MN',
 '1914 Clinton ace s, Minneapolis, MN',
 '3404 Holmes, Minneapolis, MN',
 '3532 Holmes, Minneapolis, MN',
 '1220 GRAND ST NE, Minneapolis, MN',
 '1217 talmage ave s e, Minneapolis, MN',
 '3112 Holmes, Minneapolis, MN',
 '128 9th ave ne, Minneapolis, MN',
 '2318 N 4th st, Minneapolis, MN',
 '2222 N 4th st, Minneapolis, MN',
 '2214 N 4th st, Minneapolis, MN',
 '3118 Holmes, Minneapolis, MN',
 '3554 Holmes, Minneapolis, MN',
 '2210 N 4th st, Minneapolis, MN',
 '1047 13th ave s e, Minneapolis, MN',
 '3217 HOLMES, Minneapolis, MN',
 '1033 16th ave s e, Minneapolis, MN',
 '421 giarad ter, Minneapolis, MN',
 '638 pol st ne, Minneapolis, MN',
 '1502 e 33rd st, Minneapolis, MN',
 '3228 15th a ve s, Minneapolis, MN',
 '1108 14th ave s e, Minneapolis, MN',
 '3142 16tj ave, Minneapolis, MN',
 '204 E 18th st, Minneapolis, MN',
 '612 Knox ave n, Minneapolis, MN',
 '1518 5th st s.e., Minneapolis, MN',
 '1048 16th ave s e, Minneapolis, MN',
 '1074 14th ave s e, Minneapolis, MN',
 '1908 Neuton Ave N, Minneapolis, MN',
 '1056 24th ave s e, Minneapolis, MN',
 '1329 7 th se, Minneapolis, MN',
 '7th and 14th ST SE, Minneapolis, MN',
 '1015 16th ave s e, Minneapolis, MN',
 "84'6 8th Ave n, Minneapolis, MN",
 '705 Lyndale place, Minneapolis, MN',
 '929 12th ave s e, Minneapolis, MN',
 '1101 22nd ave s e, Minneapolis, MN',
 '2737 peirce st ne, Minneapolis, MN',
 '2653 james abe n, Minneapolis, MN',
 '33oak grove st, Minneapolis, MN']

In [43]:
from geopy.geocoders import GoogleV3
geolocator = GoogleV3(api_key="AIzaSyC-_yUJpJLpXWeGuFUQA99hBAwZvffKP5I")

In [46]:
result = geolocator.geocode('chicago ave s/34th st e, Minneapolis, MN')

In [48]:
result.latitude

44.941456

In [49]:
result.longitude

-93.262657